### ISSUE TITLE
it has some question when i git your file.

### ISSUE THREAD

**Issue by baozifei** [phylib/PI-scenario#1]
Hello, i am a student in  University of Science and Technology of China,Hefei, China.My name is Jinyang Lv.
    I have some question when i git your file . When i do git@gitlab.itec.aau.at:philipp-moll/PI-scenario.git , the terminal displays that  git@gitlab.itec.aau.at's password: .but i dont know the password.Can you help solve the question ?

**Comment by phylib** [comment]
Sorry, the link in the `README` was referring to the wrong repository. Please try again with `https://github.com/phylib/PI-scenario.git`. I've updated the link in the manual.

**Comment by baozifei** [comment]
i am sorry for the late reply because that i am new for the github and i do not use this mailbox often.
i sincerely thank you for your share. i will read the document carefully and discuss with you .




jinyang_lv@foxmail.com
 
From: Philipp Moll
Date: 2017-11-02 14:54
To: phylib/PI-scenario
CC: baozifei; Author
Subject: Re: [phylib/PI-scenario] it has some question when i git your file. (#1)
Closed #1.
